CREATE TABLE SURVEY (
  ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(255),
  DESCRIPTION VARCHAR(255),
  CREATION_DATE DATE,
  EXPIRATION_DATE DATE
);

CREATE TABLE QUESTIONS (
  ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  DESCRIPTION VARCHAR(255),
  SURVEY_ID INTEGER,
  CONSTRAINT FOREIGN KEY (SURVEY_ID) REFERENCES SURVEY(ID)
);