CREATE TABLE ANSWER (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  CORRECT TINYINT(1),
  USER_ANSWER VARCHAR(1000),
  SCALE INT,
  QUESTION_ID INT,
  CONSTRAINT FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(ID)
);